#include "OFS_StringsGenerated.h"
std::array<const char*, static_cast<uint32_t>(Tr::MAX_STRING_COUNT)> OFS_DefaultStrings::Default =
{
    R"(%%this should not be displayed%%)",
	R"(About)",
	R"(Latest release)",
	R"(OFS Log Output)",
	R"(Add/Edit actions)",
	R"(Add/Edit action)",
	R"(Add action)",
	R"(Remove actions)",
	R"(Remove action)",
	R"(Mouse moved actions)",
	R"(Actions moved)",
	R"(Cut selection)",
	R"(Remove selection)",
	R"(Paste selection)",
	R"(Equalize)",
	R"(Invert)",
	R"(Isolate)",
	R"(Top points)",
	R"(Mid points)",
	R"(Bottom points)",
	R"(Generate actions)",
	R"(Frame align)",
	R"(Range extend)",
	R"(Repeat stroke)",
	R"(Move to current position)",
	R"(Simplify)",
	R"(Lua script)",
	R"(Redo stack)",
	R"(Undo stack)",
	R"(Undo/Redo history)",
	R"(T-Code)",
	R"(Port)",
	R"(Open port)",
	R"(Limits)",
	R"(Linear limits)",
	R"(Rotation limits)",
	R"(Vibration limits)",
	R"(Global settings)",
	R"(Delay)",
	R"(A / X)",
	R"(B / Circle)",
	R"(X / Square)",
	R"(Y / Triangle)",
	R"(Back / Share)",
	R"(Guide)",
	R"(Start)",
	R"(Leftstick)",
	R"(Rightstick)",
	R"(Leftshoulder)",
	R"(Rightshoulder)",
	R"(DPAD Up)",
	R"(DPAD Down)",
	R"(DPAD Left)",
	R"(DPAD Right)",
	R"(- Not set -)",
	R"(Ctrl)",
	R"(Alt)",
	R"(Shift)",
	R"(Key is in use)",
	R"(Key already bound for [%s])",
	R"(Button is in use)",
	R"(Button already bound for [%s])",
	R"(Description)",
	R"(Keyboard)",
	R"(Active)",
	R"(- Not set -)",
	R"(Change key)",
	R"(Press any key...
Escape to exit.)",
	R"(Here modifiers can be configured which change certain behaviour.)",
	R"(You can only use Shift, Ctrl & Alt.)",
	R"(Keys)",
	R"(Bindings)",
	R"(You can use CTRL, SHIFT & ALT as modifiers.)",
	R"(Only controller buttons can be bound. The DPAD directions count as a buttons.)",
	R"(The configuration gets saved everytime a change is made.)",
	R"(If you wan't to revert to the defaults, you'll have to delete the config.)",
	R"(Filter)",
	R"(Modifiers)",
	R"(Action)",
	R"(Controller)",
	R"(Ignore repeats)",
	R"(Change button)",
	R"(Press any button...
Escape to clear.)",
	R"(Running task)",
	R"(This may take a while...)",
	R"(Options)",
	R"(Auto-scroll)",
	R"(Clear)",
	R"(Copy)",
	R"(Used)",
	R"(Allocated)",
	R"(Scripts)",
	R"(Rendering)",
	R"(Show actions)",
	R"(Spline mode)",
	R"(Show video position)",
	R"(Waveform)",
	R"(Settings)",
	R"(Scale)",
	R"(Color)",
	R"(Enable waveform)",
	R"(Min: %d)",
	R"(Max: %d)",
	R"(Tickrate (Hz))",
	R"(Spline)",
	R"(Smooth motion instead of linear.)",
	R"(Remap)",
	R"(Remap script to use the full range.
i.e. scripts using the range 10 to 90 become 0 to 100.)",
	R"(Negative: Backward in time.
Positive: Forward in time.)",
	R"(Outputs)",
	R"(You can right click sliders.)",
	R"(Rebalance)",
	R"(Balance around 500 even with unevenly spread limits.)",
	R"(only)",
	R"((Frame overlay only)
Shows a red line where the current frame is.
More of a debugging feature.)",
	R"(Processing audio...)",
	R"(Update waveform)",
	R"(Positions)",
	R"(Loop A set)",
	R"(Loop B set)",
	R"(Lock)",
	R"(Click to enable video)",
	R"(Loop cleared)",
	R"(Player)",
	R"(Speed)",
	R"(Timeline)",
	R"(Time)",
	R"(Controls)",
	R"(seconds)",
	R"(Exporting clips)",
	R"(Project)",
	R"(Media)",
	R"(Change default location)",
	R"(Change location)",
	R"(Scripting mode)",
	R"(Default)",
	R"(Alternating)",
	R"(Dynamic injection)",
	R"(Recording)",
	R"(Scripting overlay)",
	R"(Frame)",
	R"(Tempo)",
	R"(None)",
	R"(Offset (ms))",
	R"(Applies an offset to actions inserted while the video is playing.
- : inserts earlier
+ : inserts later)",
	R"(Mirror mode)",
	R"(Mirrors add/edit/remove action across all loaded scripts.)",
	R"(Target speed (units/s))",
	R"(Up/Down speed bias)",
	R"(Top)",
	R"(Bottom)",
	R"(Next point)",
	R"(Next point is at %d)",
	R"(Next point is %s)",
	R"(inverted)",
	R"(not inverted)",
	R"(Fixed range)",
	R"(Context sensitive)",
	R"(Alternates based on the previous action.)",
	R"(Mode)",
	R"(Mouse)",
	R"(Controller deadzone)",
	R"(Deadzone)",
	R"(Center)",
	R"(Two axes)",
	R"(Recording pitch & roll at once.
Only works with a controller.)",
	R"(Record on play)",
	R"(X / Y)",
	R"(Position)",
	R"(Recording active)",
	R"(Recording paused)",
	R"(Statistics)",
	R"(Action editor)",
	R"(Dynamic)",
	R"(Actions)",
	R"(Core)",
	R"(Navigation)",
	R"(Utility)",
	R"(Moving)",
	R"(Special)",
	R"(Videoplayer)",
	R"(Extensions)",
	R"(Controller)",
	R"(Remove action)",
	R"(Action at -100)",
	R"(Action at -80)",
	R"(Action at -60)",
	R"(Action at -40)",
	R"(Action at 20)",
	R"(Action at 0)",
	R"(Action at 20)",
	R"(Action at 40)",
	R"(Action at 60)",
	R"(Action at 80)",
	R"(Action at 100)",
	R"(Save project)",
	R"(Quick export)",
	R"(Sync time with player)",
	R"(Cycle forward loaded scripts)",
	R"(Cycle backward loaded scripts)",
	R"(Previous action)",
	R"(Next action)",
	R"(Previous action (multi))",
	R"(Next action (multi))",
	R"(Previous frame)",
	R"(Next frame)",
	R"(Fast step)",
	R"(Fast backstep)",
	R"(Undo)",
	R"(Redo)",
	R"(Copy)",
	R"(Paste)",
	R"(Cut)",
	R"(Paste exact)",
	R"(Select all)",
	R"(Deselect all)",
	R"(Select all left)",
	R"(Select all right)",
	R"(Select top points)",
	R"(Select bottom points)",
	R"(Select middle points)",
	R"(Toggle mirror mode)",
	R"(Save frame as image)",
	R"(Cycle subtitles)",
	R"(Toggle fullscreen)",
	R"(Move actions +10 up)",
	R"(Move actions -10 down)",
	R"(Move actions +5 up)",
	R"(Move actions -5 down)",
	R"(Move actions left with snapping)",
	R"(Move actions right with snapping)",
	R"(Move actions left)",
	R"(Move actions right)",
	R"(Move actions up)",
	R"(Move actions down)",
	R"(Move to current position)",
	R"(Equalize actions)",
	R"(Invert actions)",
	R"(Isolate action)",
	R"(Repeat stroke)",
	R"(Play / Pause)",
	R"(Playback speed -10%)",
	R"(Playback speed +10%)",
	R"(Go to the start)",
	R"(Go to the end)",
	R"(Reload enabled extensions)",
	R"(Toggle controller navigation)",
	R"(Forward 1 second)",
	R"(Backward 1 second)",
	R"(Add action)",
	R"(Toggle recording mode)",
	R"(Controller selection)",
	R"(Set current playback speed)",
	R"(Point timeline)",
	R"(Simulator)",
	R"(Click drag/add point in the timeline)",
	R"(Click simulator to add a point)",
	R"(Project has unsaved edits)",
	R"(The current project has unsaved edits.)",
	R"(Unsaved changes)",
	R"(Do you want to save and exit?)",
	R"(File not found)",
	R"(Couldn’t find file)",
	R"(OpenFunscripter failed to import.)",
	R"(Failed to import)",
	R"(Failed to load)",
	R"(The project failed to load.)",
	R"(Failed to find video)",
	R"(The video was not found.
Please pick the correct video.)",
	R"(Choose output directory)",
	R"(Pick different media)",
	R"(File)",
	R"(Open project)",
	R"(Save)",
	R"(Close project)",
	R"(Wrong file)",
	R"(The file isn’t a project file.)",
	R"(Import video/script)",
	R"(Recent files)",
	R"(No recent files)",
	R"(Save project)",
	R"(Export...)",
	R"(Quick export)",
	R"(Exports all scripts as .funscript in their default paths.)",
	R"(Export active script)",
	R"(Export as UFOTW script)",
	R"(Export all)",
	R"(Auto Backup in %d seconds)",
	R"(Auto Backup)",
	R"(Open backup directory)",
	R"(Configure)",
	R"(Add...)",
	R"(Shortcuts)",
	R"(Add new)",
	R"(Add new funscript)",
	R"(Add existing)",
	R"(Add existing funscripts)",
	R"(If the script wasn’t previously exported, this can’t be reverted.
Continue?)",
	R"(Remove)",
	R"(Remove script)",
	R"(Edit)",
	R"(Save frame as image)",
	R"(Open screenshot directory)",
	R"(Save heatmap)",
	R"(Undo)",
	R"(Redo)",
	R"(Cut)",
	R"(Paste)",
	R"(Select)",
	R"(Select all)",
	R"(Deselect all)",
	R"(Special)",
	R"(Select all left)",
	R"(Select all right)",
	R"(Set selection start)",
	R"(Set selection end)",
	R"(Top points only)",
	R"(Mid points only)",
	R"(Bottom points only)",
	R"(Bookmarks)",
	R"(Export clip)",
	R"(Name)",
	R"(Add bookmark)",
	R"(Create interval for "%s")",
	R"(Go to...)",
	R"(No bookmarks)",
	R"(Always show labels)",
	R"(Delete all bookmarks)",
	R"(View)",
	R"(Metadata)",
	R"(Draw video)",
	R"(Reset video position)",
	R"(Video mode)",
	R"(Full)",
	R"(Left pane)",
	R"(Right pane)",
	R"(Top pane)",
	R"(Bottom pane)",
	R"(VR)",
	R"(Debug)",
	R"(Metrics)",
	R"(Log output)",
	R"(Fullscreen)",
	R"(Preferences)",
	R"(Repeat rate)",
	R"(Controller connected!)",
	R"(Extensions)",
	R"(Developer mode)",
	R"(Show logs)",
	R"(Enable extra functionality for extension developement.)",
	R"(Extension directory)",
	R"(Enabled)",
	R"(Show window)",
	R"(Open directory)",
	R"(Navigation)",
	R"(Scripting)",
	R"(unsaved changes %d minutes ago)",
	R"(Metadata editor)",
	R"(Title)",
	R"(Duration)",
	R"(Creator)",
	R"(Url)",
	R"(Video url)",
	R"(Notes)",
	R"(License)",
	R"(Free)",
	R"(Paid)",
	R"(None)",
	R"(Tags)",
	R"(Add)",
	R"(Performers)",
	R"(Save template)",
	R"(Saves all current values as defaults for later.)",
	R"(Commit)",
	R"(Interval)",
	R"(Close without saving?)",
	R"(Do you want to save the current project?)",
	R"(Configuration)",
	R"(Reset)",
	R"(Move)",
	R"(Distance)",
	R"(Global yaw)",
	R"(Global pitch)",
	R"(Box)",
	R"(Container)",
	R"(Twist)",
	R"(Roll deg)",
	R"(Pitch deg)",
	R"(Twist deg)",
	R"(Roll)",
	R"(Pitch)",
	R"(Yaw)",
	R"(Insert current position)",
	R"(Scroll (%))",
	R"(You can use the mousewheel on the sliders above.)",
	R"(Extension log output)",
	R"(Error)",
	R"(Try reloading)",
	R"(Reload)",
	R"(BPM)",
	R"(Offset)",
	R"(Snap)",
	R"(unknown error)",
	R"(ffmpeg.exe was not found.
Do you want to download it?)",
	R"(Bindable functions)",
	R"(Yes)",
	R"(Failed to download from https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip)",
	R"(Done)",
	R"(ffmpeg.exe was successfully extracted.)",
	R"(Failed to extract ffmpeg.exe.)",
	R"(Extracting uses tar.exe.
It will fail if it's not on your system.)",
	R"(Download ffmpeg?)",
	R"(whole measures)",
	R"(2nd measures)",
	R"(4th measures)",
	R"(8th measures)",
	R"(12th measures)",
	R"(16th measures)",
	R"(24th measures)",
	R"(32nd measures)",
	R"(48th measures)",
	R"(64th measures)",
	R"(Load config)",
	R"(Save config)",
	R"(Save simulator configuration)",
	R"(Do you want do save the current config?
This will override any existing default config.)",
	R"(Lines)",
	R"(Text)",
	R"(Front)",
	R"(Back)",
	R"(Border)",
	R"(Indicator)",
	R"(Line)",
	R"(Width)",
	R"(Opacity)",
	R"(Extra lines)",
	R"(Vanilla)",
	R"(Show position)",
	R"(The original simulator from day one.)",
	R"(Reset to defaults)",
	R"(Simulator)",
	R"(Application)",
	R"(Dark mode)",
	R"(Light mode)",
	R"(Higher frame rate makes OFS feel "snappier" because input gets processed more frequently.)",
	R"(Vsync)",
	R"(Limits frame rate to the refresh rate of the monitor.
Frame limit is ignored.)",
	R"(Frame limit)",
	R"(This limits the frame rate OFS is running at.)",
	R"(Font)",
	R"(Change)",
	R"(Choose font)",
	R"(Default font)",
	R"(Font size)",
	R"(Force hardware decoding (Requires program restart))",
	R"(May cause crashes on some systems.)",
	R"(Fast frame step)",
	R"(Amount of frames to skip with fast step.)",
	R"(Show metadata dialog on new project)",
	R"(Range extender)",
	R"(Simplify (Ramer-Douglas-Peucker))",
	R"(Range)",
	R"(Select atleast 5 actions to extend.)",
	R"(Epsilon)",
	R"(Select atleast 5 actions to simplify.)",
	R"(Special functions)",
	R"(Memory usage)",
	R"(Update)",
	R"(slowest)",
	R"(Language)",
	R"(Reload current translation)",
	R"(Directory)",
	R"(Highlight treshold)",
	R"(Max speed highlight)",
	R"(FPS override)",
	R"(Time spent)",
	R"(Show lines)",
	R"(Show points)",
	R"(Clear recent files)",
	R"(Open...)",
	R"(Add/Edit trigger)",
	R"(Validate)",
	R"(ok)",
	R"(The following triggers have no corresponding actions.)",
	R"(Delete)",
	R"(Repeat)",
	R"(Websocket API)",
	R"(Server active)",
	R"(Clients connected)",
	R"(Start)",
	R"(End)",
	R"(Total)",
	R"(Remove chapter)",
	R"(Do you want to remove the chapter?)",
	R"(Remove bookmark)",
	R"(Do you want to remove the bookmark?)",
	R"(Add chapter)",
	R"(Add bookmark)",
	R"(Set size)",
	R"(Save heatmap with chapters)",
	R"(Chapters)",
	R"(Chapter)",
	R"(Begin)",
	R"(Chapters)",
	R"(Create bookmark)",
	R"(Create chapter)",
	
};

std::unordered_map<std::string, Tr> OFS_DefaultStrings::KeyMapping =
{
	{"INVALID_TR", Tr::INVALID_TR},
	{"ABOUT", Tr::ABOUT},
	{"LATEST_RELEASE", Tr::LATEST_RELEASE},
	{"OFS_LOG_OUTPUT", Tr::OFS_LOG_OUTPUT},
	{"ADD_EDIT_ACTIONS", Tr::ADD_EDIT_ACTIONS},
	{"ADD_EDIT_ACTION", Tr::ADD_EDIT_ACTION},
	{"ADD_ACTION", Tr::ADD_ACTION},
	{"REMOVE_ACTIONS", Tr::REMOVE_ACTIONS},
	{"REMOVE_ACTION", Tr::REMOVE_ACTION},
	{"MOUSE_MOVED_ACTIONS", Tr::MOUSE_MOVED_ACTIONS},
	{"ACTIONS_MOVED", Tr::ACTIONS_MOVED},
	{"CUT_SELECTION", Tr::CUT_SELECTION},
	{"REMOVE_SELECTION", Tr::REMOVE_SELECTION},
	{"PASTE_SELECTION", Tr::PASTE_SELECTION},
	{"EQUALIZE", Tr::EQUALIZE},
	{"INVERT", Tr::INVERT},
	{"ISOLATE", Tr::ISOLATE},
	{"TOP_POINTS", Tr::TOP_POINTS},
	{"MID_POINTS", Tr::MID_POINTS},
	{"BOTTOM_POINTS", Tr::BOTTOM_POINTS},
	{"GENERATE_ACTIONS", Tr::GENERATE_ACTIONS},
	{"FRAME_ALIGN", Tr::FRAME_ALIGN},
	{"RANGE_EXTEND", Tr::RANGE_EXTEND},
	{"REPEAT_STROKE", Tr::REPEAT_STROKE},
	{"MOVE_TO_CURRENT_POSITION", Tr::MOVE_TO_CURRENT_POSITION},
	{"SIMPLIFY", Tr::SIMPLIFY},
	{"LUA_SCRIPT", Tr::LUA_SCRIPT},
	{"REDO_STACK", Tr::REDO_STACK},
	{"UNDO_STACK", Tr::UNDO_STACK},
	{"UNDO_REDO_HISTORY", Tr::UNDO_REDO_HISTORY},
	{"T_CODE", Tr::T_CODE},
	{"PORT", Tr::PORT},
	{"OPEN_PORT", Tr::OPEN_PORT},
	{"LIMITS", Tr::LIMITS},
	{"LINEAR_LIMITS", Tr::LINEAR_LIMITS},
	{"ROTATION_LIMITS", Tr::ROTATION_LIMITS},
	{"VIBRATION_LIMITS", Tr::VIBRATION_LIMITS},
	{"GLOBAL_SETTINGS", Tr::GLOBAL_SETTINGS},
	{"DELAY", Tr::DELAY},
	{"CONTROLLER_BUTTON_A", Tr::CONTROLLER_BUTTON_A},
	{"CONTROLLER_BUTTON_B", Tr::CONTROLLER_BUTTON_B},
	{"CONTROLLER_BUTTON_X", Tr::CONTROLLER_BUTTON_X},
	{"CONTROLLER_BUTTON_Y", Tr::CONTROLLER_BUTTON_Y},
	{"CONTROLLER_BUTTON_BACK", Tr::CONTROLLER_BUTTON_BACK},
	{"CONTROLLER_BUTTON_GUIDE", Tr::CONTROLLER_BUTTON_GUIDE},
	{"CONTROLLER_BUTTON_START", Tr::CONTROLLER_BUTTON_START},
	{"CONTROLLER_BUTTON_LEFTSTICK", Tr::CONTROLLER_BUTTON_LEFTSTICK},
	{"CONTROLLER_BUTTON_RIGHTSTICK", Tr::CONTROLLER_BUTTON_RIGHTSTICK},
	{"CONTROLLER_BUTTON_LEFTSHOULDER", Tr::CONTROLLER_BUTTON_LEFTSHOULDER},
	{"CONTROLLER_BUTTON_RIGHTSHOULDER", Tr::CONTROLLER_BUTTON_RIGHTSHOULDER},
	{"CONTROLLER_BUTTON_DPAD_UP", Tr::CONTROLLER_BUTTON_DPAD_UP},
	{"CONTROLLER_BUTTON_DPAD_DOWN", Tr::CONTROLLER_BUTTON_DPAD_DOWN},
	{"CONTROLLER_BUTTON_DPAD_LEFT", Tr::CONTROLLER_BUTTON_DPAD_LEFT},
	{"CONTROLLER_BUTTON_DPAD_RIGHT", Tr::CONTROLLER_BUTTON_DPAD_RIGHT},
	{"CONTROLLER_NOT_SET", Tr::CONTROLLER_NOT_SET},
	{"KEY_MOD_CTRL", Tr::KEY_MOD_CTRL},
	{"KEY_MOD_ALT", Tr::KEY_MOD_ALT},
	{"KEY_MOD_SHIFT", Tr::KEY_MOD_SHIFT},
	{"KEY_ALREADY_IN_USE", Tr::KEY_ALREADY_IN_USE},
	{"KEY_ALREADY_IN_USE_MSG", Tr::KEY_ALREADY_IN_USE_MSG},
	{"BUTTON_ALREADY_IN_USE", Tr::BUTTON_ALREADY_IN_USE},
	{"BUTTON_ALREADY_IN_USE_MSG", Tr::BUTTON_ALREADY_IN_USE_MSG},
	{"DESCRIPTION", Tr::DESCRIPTION},
	{"KEYBOARD", Tr::KEYBOARD},
	{"ACTIVE", Tr::ACTIVE},
	{"KEY_NOT_SET", Tr::KEY_NOT_SET},
	{"CHANGE_KEY", Tr::CHANGE_KEY},
	{"CHANGE_KEY_MSG", Tr::CHANGE_KEY_MSG},
	{"PASSIVE_BINDING_TXT1", Tr::PASSIVE_BINDING_TXT1},
	{"PASSIVE_BINDING_TXT2", Tr::PASSIVE_BINDING_TXT2},
	{"KEYS", Tr::KEYS},
	{"BINDINGS", Tr::BINDINGS},
	{"BINDING_TXT1", Tr::BINDING_TXT1},
	{"BINDING_TXT2", Tr::BINDING_TXT2},
	{"BINDING_TXT3", Tr::BINDING_TXT3},
	{"BINDING_TXT4", Tr::BINDING_TXT4},
	{"FILTER", Tr::FILTER},
	{"MODIFIERS", Tr::MODIFIERS},
	{"ACTION", Tr::ACTION},
	{"CONTROLLER", Tr::CONTROLLER},
	{"IGNORE_REPEATS", Tr::IGNORE_REPEATS},
	{"CHANGE_BUTTON", Tr::CHANGE_BUTTON},
	{"CHANGE_BUTTON_MSG", Tr::CHANGE_BUTTON_MSG},
	{"RUNNING_TASK", Tr::RUNNING_TASK},
	{"THIS_MAY_TAKE_A_WHILE", Tr::THIS_MAY_TAKE_A_WHILE},
	{"OPTIONS", Tr::OPTIONS},
	{"AUTO_SCROLL", Tr::AUTO_SCROLL},
	{"CLEAR", Tr::CLEAR},
	{"COPY", Tr::COPY},
	{"USED", Tr::USED},
	{"ALLOCATED", Tr::ALLOCATED},
	{"SCRIPTS", Tr::SCRIPTS},
	{"RENDERING", Tr::RENDERING},
	{"SHOW_ACTIONS", Tr::SHOW_ACTIONS},
	{"SPLINE_MODE", Tr::SPLINE_MODE},
	{"SHOW_VIDEO_POSITION", Tr::SHOW_VIDEO_POSITION},
	{"WAVEFORM", Tr::WAVEFORM},
	{"SETTINGS", Tr::SETTINGS},
	{"SCALE", Tr::SCALE},
	{"COLOR", Tr::COLOR},
	{"ENABLE_WAVEFORM", Tr::ENABLE_WAVEFORM},
	{"MIN_INT_FMT", Tr::MIN_INT_FMT},
	{"MAX_INT_FMT", Tr::MAX_INT_FMT},
	{"TCODE_TICKRATE", Tr::TCODE_TICKRATE},
	{"SPLINE", Tr::SPLINE},
	{"SPLINE_TOOLTIP", Tr::SPLINE_TOOLTIP},
	{"REMAP", Tr::REMAP},
	{"REMAP_TOOLTIP", Tr::REMAP_TOOLTIP},
	{"DELAY_TOOLTIP", Tr::DELAY_TOOLTIP},
	{"OUTPUTS", Tr::OUTPUTS},
	{"YOU_CAN_RIGHT_CLICK_SLIDERS_TOOLTIP", Tr::YOU_CAN_RIGHT_CLICK_SLIDERS_TOOLTIP},
	{"REBALANCE", Tr::REBALANCE},
	{"REBALANCE_TOOLTIP", Tr::REBALANCE_TOOLTIP},
	{"GAMEPAD_ONLY", Tr::GAMEPAD_ONLY},
	{"SHOW_VIDEO_POSITION_TOOLTIP", Tr::SHOW_VIDEO_POSITION_TOOLTIP},
	{"PROCESSING_AUDIO", Tr::PROCESSING_AUDIO},
	{"UPDATE_WAVEFORM", Tr::UPDATE_WAVEFORM},
	{"POSITIONS", Tr::POSITIONS},
	{"LOOP_A_SET", Tr::LOOP_A_SET},
	{"LOOP_B_SET", Tr::LOOP_B_SET},
	{"LOCK", Tr::LOCK},
	{"CLICK_TO_ENABLE_VIDEO", Tr::CLICK_TO_ENABLE_VIDEO},
	{"LOOP_CLEARED", Tr::LOOP_CLEARED},
	{"VIDEOPLAYER", Tr::VIDEOPLAYER},
	{"SPEED", Tr::SPEED},
	{"TIMELINE", Tr::TIMELINE},
	{"TIME", Tr::TIME},
	{"CONTROLS", Tr::CONTROLS},
	{"TIMELINE_SECONDS", Tr::TIMELINE_SECONDS},
	{"TASK_EXPORTING_CLIPS", Tr::TASK_EXPORTING_CLIPS},
	{"PROJECT", Tr::PROJECT},
	{"MEDIA", Tr::MEDIA},
	{"CHANGE_DEFAULT_LOCATION", Tr::CHANGE_DEFAULT_LOCATION},
	{"CHANGE_LOCATION", Tr::CHANGE_LOCATION},
	{"SCRIPTING_MODE", Tr::SCRIPTING_MODE},
	{"DEFAULT_MODE", Tr::DEFAULT_MODE},
	{"ALTERNATING_MODE", Tr::ALTERNATING_MODE},
	{"DYNAMIC_INJECTION_MODE", Tr::DYNAMIC_INJECTION_MODE},
	{"RECORDING_MODE", Tr::RECORDING_MODE},
	{"SCRIPTING_OVERLAY", Tr::SCRIPTING_OVERLAY},
	{"FRAME_OVERLAY", Tr::FRAME_OVERLAY},
	{"TEMPO_OVERLAY", Tr::TEMPO_OVERLAY},
	{"EMPTY_OVERLAY", Tr::EMPTY_OVERLAY},
	{"OFFSET_MS", Tr::OFFSET_MS},
	{"OFFSET_TOOLTIP", Tr::OFFSET_TOOLTIP},
	{"MIRROR_MODE", Tr::MIRROR_MODE},
	{"MIRROR_MODE_TOOLTIP", Tr::MIRROR_MODE_TOOLTIP},
	{"DI_TARGET_SPEED", Tr::DI_TARGET_SPEED},
	{"DI_UP_DOWN_BIAS", Tr::DI_UP_DOWN_BIAS},
	{"TOP", Tr::TOP},
	{"BOTTOM", Tr::BOTTOM},
	{"NEXT_POINT", Tr::NEXT_POINT},
	{"NEXT_POINT_AT_FMT", Tr::NEXT_POINT_AT_FMT},
	{"NEXT_POINT_IS_FMT", Tr::NEXT_POINT_IS_FMT},
	{"INVERTED", Tr::INVERTED},
	{"NOT_INVERTED", Tr::NOT_INVERTED},
	{"FIXED_RANGE", Tr::FIXED_RANGE},
	{"CONTEXT_SENSITIVE", Tr::CONTEXT_SENSITIVE},
	{"CONTEXT_SENSITIVE_TOOLTIP", Tr::CONTEXT_SENSITIVE_TOOLTIP},
	{"MODE", Tr::MODE},
	{"MOUSE", Tr::MOUSE},
	{"CONTROLLER_DEADZONE", Tr::CONTROLLER_DEADZONE},
	{"DEADZONE", Tr::DEADZONE},
	{"CENTER", Tr::CENTER},
	{"TWO_AXES", Tr::TWO_AXES},
	{"TWO_AXES_TOOLTIP", Tr::TWO_AXES_TOOLTIP},
	{"RECORD_ON_PLAY", Tr::RECORD_ON_PLAY},
	{"TWO_AXES_AXES", Tr::TWO_AXES_AXES},
	{"POSITION", Tr::POSITION},
	{"RECORDING_ACTIVE", Tr::RECORDING_ACTIVE},
	{"RECORDING_PAUSED", Tr::RECORDING_PAUSED},
	{"STATISTICS", Tr::STATISTICS},
	{"ACTION_EDITOR", Tr::ACTION_EDITOR},
	{"DYNAMIC_BINDING_GROUP", Tr::DYNAMIC_BINDING_GROUP},
	{"ACTIONS_BINDING_GROUP", Tr::ACTIONS_BINDING_GROUP},
	{"CORE_BINDING_GROUP", Tr::CORE_BINDING_GROUP},
	{"NAVIGATION_BINDING_GROUP", Tr::NAVIGATION_BINDING_GROUP},
	{"UTILITY_BINDING_GROUP", Tr::UTILITY_BINDING_GROUP},
	{"MOVING_BINDING_GROUP", Tr::MOVING_BINDING_GROUP},
	{"SPECIAL_BINDING_GROUP", Tr::SPECIAL_BINDING_GROUP},
	{"VIDEOPLAYER_BINDING_GROUP", Tr::VIDEOPLAYER_BINDING_GROUP},
	{"EXTENSIONS_BINDING_GROUP", Tr::EXTENSIONS_BINDING_GROUP},
	{"CONTROLLER_BINDING_GROUP", Tr::CONTROLLER_BINDING_GROUP},
	{"ACTION_REMOVE_ACTION", Tr::ACTION_REMOVE_ACTION},
	{"ACTION_ACTION_MINUS100", Tr::ACTION_ACTION_MINUS100},
	{"ACTION_ACTION_MINUS80", Tr::ACTION_ACTION_MINUS80},
	{"ACTION_ACTION_MINUS60", Tr::ACTION_ACTION_MINUS60},
	{"ACTION_ACTION_MINUS40", Tr::ACTION_ACTION_MINUS40},
	{"ACTION_ACTION_MINUS20", Tr::ACTION_ACTION_MINUS20},
	{"ACTION_ACTION_0", Tr::ACTION_ACTION_0},
	{"ACTION_ACTION_PLUS20", Tr::ACTION_ACTION_PLUS20},
	{"ACTION_ACTION_PLUS40", Tr::ACTION_ACTION_PLUS40},
	{"ACTION_ACTION_PLUS60", Tr::ACTION_ACTION_PLUS60},
	{"ACTION_ACTION_PLUS80", Tr::ACTION_ACTION_PLUS80},
	{"ACTION_ACTION_PLUS100", Tr::ACTION_ACTION_PLUS100},
	{"ACTION_SAVE_PROJECT", Tr::ACTION_SAVE_PROJECT},
	{"ACTION_QUICK_EXPORT", Tr::ACTION_QUICK_EXPORT},
	{"ACTION_SYNC_TIME_WITH_PLAYER", Tr::ACTION_SYNC_TIME_WITH_PLAYER},
	{"ACTION_CYCLE_FORWARD_LOADED_SCRIPTS", Tr::ACTION_CYCLE_FORWARD_LOADED_SCRIPTS},
	{"ACTION_CYCLE_BACKWARD_LOADED_SCRIPTS", Tr::ACTION_CYCLE_BACKWARD_LOADED_SCRIPTS},
	{"ACTION_PREVIOUS_ACTION", Tr::ACTION_PREVIOUS_ACTION},
	{"ACTION_NEXT_ACTION", Tr::ACTION_NEXT_ACTION},
	{"ACTION_PREVIOUS_ACTION_MULTI", Tr::ACTION_PREVIOUS_ACTION_MULTI},
	{"ACTION_NEXT_ACTION_MULTI", Tr::ACTION_NEXT_ACTION_MULTI},
	{"ACTION_PREV_FRAME", Tr::ACTION_PREV_FRAME},
	{"ACTION_NEXT_FRAME", Tr::ACTION_NEXT_FRAME},
	{"ACTION_FAST_STEP", Tr::ACTION_FAST_STEP},
	{"ACTION_FAST_BACKSTEP", Tr::ACTION_FAST_BACKSTEP},
	{"ACTION_UNDO", Tr::ACTION_UNDO},
	{"ACTION_REDO", Tr::ACTION_REDO},
	{"ACTION_COPY", Tr::ACTION_COPY},
	{"ACTION_PASTE", Tr::ACTION_PASTE},
	{"ACTION_CUT", Tr::ACTION_CUT},
	{"ACTION_PASTE_EXACT", Tr::ACTION_PASTE_EXACT},
	{"ACTION_SELECT_ALL", Tr::ACTION_SELECT_ALL},
	{"ACTION_DESELECT_ALL", Tr::ACTION_DESELECT_ALL},
	{"ACTION_SELECT_ALL_LEFT", Tr::ACTION_SELECT_ALL_LEFT},
	{"ACTION_SELECT_ALL_RIGHT", Tr::ACTION_SELECT_ALL_RIGHT},
	{"ACTION_SELECT_TOP", Tr::ACTION_SELECT_TOP},
	{"ACTION_SELECT_BOTTOM", Tr::ACTION_SELECT_BOTTOM},
	{"ACTION_SELECT_MID", Tr::ACTION_SELECT_MID},
	{"ACTION_TOGGLE_MIRROR_MODE", Tr::ACTION_TOGGLE_MIRROR_MODE},
	{"ACTION_SAVE_FRAME", Tr::ACTION_SAVE_FRAME},
	{"ACTION_CYCLE_SUBTITLES", Tr::ACTION_CYCLE_SUBTITLES},
	{"ACTION_TOGGLE_FULLSCREEN", Tr::ACTION_TOGGLE_FULLSCREEN},
	{"ACTION_MOVE_UP_10", Tr::ACTION_MOVE_UP_10},
	{"ACTION_MOVE_DOWN_10", Tr::ACTION_MOVE_DOWN_10},
	{"ACTION_MOVE_UP_5", Tr::ACTION_MOVE_UP_5},
	{"ACTION_MOVE_DOWN_5", Tr::ACTION_MOVE_DOWN_5},
	{"ACTION_MOVE_ACTIONS_LEFT_SNAP", Tr::ACTION_MOVE_ACTIONS_LEFT_SNAP},
	{"ACTION_MOVE_ACTIONS_RIGHT_SNAP", Tr::ACTION_MOVE_ACTIONS_RIGHT_SNAP},
	{"ACTION_MOVE_ACTIONS_LEFT", Tr::ACTION_MOVE_ACTIONS_LEFT},
	{"ACTION_MOVE_ACTIONS_RIGHT", Tr::ACTION_MOVE_ACTIONS_RIGHT},
	{"ACTION_MOVE_ACTIONS_UP", Tr::ACTION_MOVE_ACTIONS_UP},
	{"ACTION_MOVE_ACTIONS_DOWN", Tr::ACTION_MOVE_ACTIONS_DOWN},
	{"ACTION_MOVE_TO_CURRENT_POSITION", Tr::ACTION_MOVE_TO_CURRENT_POSITION},
	{"ACTION_EQUALIZE_ACTIONS", Tr::ACTION_EQUALIZE_ACTIONS},
	{"ACTION_INVERT_ACTIONS", Tr::ACTION_INVERT_ACTIONS},
	{"ACTION_ISOLATE_ACTION", Tr::ACTION_ISOLATE_ACTION},
	{"ACTION_REPEAT_STROKE", Tr::ACTION_REPEAT_STROKE},
	{"ACTION_TOGGLE_PLAY", Tr::ACTION_TOGGLE_PLAY},
	{"ACTION_REDUCE_PLAYBACK_SPEED", Tr::ACTION_REDUCE_PLAYBACK_SPEED},
	{"ACTION_INCREASE_PLAYBACK_SPEED", Tr::ACTION_INCREASE_PLAYBACK_SPEED},
	{"ACTION_GO_TO_START", Tr::ACTION_GO_TO_START},
	{"ACTION_GO_TO_END", Tr::ACTION_GO_TO_END},
	{"ACTION_RELOAD_ENABLED_EXTENSIONS", Tr::ACTION_RELOAD_ENABLED_EXTENSIONS},
	{"ACTION_TOGGLE_CONTROLLER_NAV", Tr::ACTION_TOGGLE_CONTROLLER_NAV},
	{"ACTION_SEEK_FORWARD_1", Tr::ACTION_SEEK_FORWARD_1},
	{"ACTION_SEEK_BACKWARD_1", Tr::ACTION_SEEK_BACKWARD_1},
	{"ACTION_ADD_ACTION_CONTROLLER", Tr::ACTION_ADD_ACTION_CONTROLLER},
	{"ACTION_TOGGLE_RECORDING_MODE", Tr::ACTION_TOGGLE_RECORDING_MODE},
	{"ACTION_CONTROLLER_SELECT", Tr::ACTION_CONTROLLER_SELECT},
	{"ACTION_SET_PLAYBACK_SPEED", Tr::ACTION_SET_PLAYBACK_SPEED},
	{"PASSIVE_GROUP_TIMELINE", Tr::PASSIVE_GROUP_TIMELINE},
	{"PASSIVE_GROUP_SIMULATOR", Tr::PASSIVE_GROUP_SIMULATOR},
	{"MOD_MOVE_OR_ADD_POINT", Tr::MOD_MOVE_OR_ADD_POINT},
	{"MOD_CLICK_SIM_ADD_PONT", Tr::MOD_CLICK_SIM_ADD_PONT},
	{"PROJECT_HAS_UNSAVED_EDITS", Tr::PROJECT_HAS_UNSAVED_EDITS},
	{"UNSAVED_EDITS_MSG", Tr::UNSAVED_EDITS_MSG},
	{"UNSAVED_CHANGES", Tr::UNSAVED_CHANGES},
	{"UNSAVED_CHANGES_MSG", Tr::UNSAVED_CHANGES_MSG},
	{"FILE_NOT_FOUND", Tr::FILE_NOT_FOUND},
	{"COULDNT_FIND_FILE", Tr::COULDNT_FIND_FILE},
	{"OFS_FAILED_TO_IMPORT", Tr::OFS_FAILED_TO_IMPORT},
	{"OFS_FAILED_TO_IMPORT_MSG", Tr::OFS_FAILED_TO_IMPORT_MSG},
	{"FAILED_TO_LOAD", Tr::FAILED_TO_LOAD},
	{"FAILED_TO_LOAD_MSG", Tr::FAILED_TO_LOAD_MSG},
	{"FAILED_TO_FIND_VIDEO", Tr::FAILED_TO_FIND_VIDEO},
	{"FAILED_TO_FIND_VIDEO_MSG", Tr::FAILED_TO_FIND_VIDEO_MSG},
	{"CHOOSE_OUTPUT_DIR", Tr::CHOOSE_OUTPUT_DIR},
	{"PICK_DIFFERENT_MEDIA", Tr::PICK_DIFFERENT_MEDIA},
	{"FILE", Tr::FILE},
	{"OPEN_PROJECT", Tr::OPEN_PROJECT},
	{"SAVE", Tr::SAVE},
	{"CLOSE_PROJECT", Tr::CLOSE_PROJECT},
	{"WRONG_FILE", Tr::WRONG_FILE},
	{"WRONG_FILE_MSG", Tr::WRONG_FILE_MSG},
	{"IMPORT_VIDEO_SCRIPT", Tr::IMPORT_VIDEO_SCRIPT},
	{"RECENT_FILES", Tr::RECENT_FILES},
	{"NO_RECENT_FILES", Tr::NO_RECENT_FILES},
	{"SAVE_PROJECT", Tr::SAVE_PROJECT},
	{"EXPORT_MENU", Tr::EXPORT_MENU},
	{"QUICK_EXPORT", Tr::QUICK_EXPORT},
	{"QUICK_EXPORT_TOOLTIP", Tr::QUICK_EXPORT_TOOLTIP},
	{"EXPORT_ACTIVE_SCRIPT", Tr::EXPORT_ACTIVE_SCRIPT},
	{"EXPORT_AS_UFOTW_SCRIPT", Tr::EXPORT_AS_UFOTW_SCRIPT},
	{"EXPORT_ALL", Tr::EXPORT_ALL},
	{"AUTO_BACKUP_TIMER_FMT", Tr::AUTO_BACKUP_TIMER_FMT},
	{"AUTO_BACKUP", Tr::AUTO_BACKUP},
	{"OPEN_BACKUP_DIR", Tr::OPEN_BACKUP_DIR},
	{"CONFIGURE", Tr::CONFIGURE},
	{"ADD_MENU", Tr::ADD_MENU},
	{"ADD_SHORTCUTS", Tr::ADD_SHORTCUTS},
	{"ADD_NEW", Tr::ADD_NEW},
	{"ADD_NEW_FUNSCRIPT", Tr::ADD_NEW_FUNSCRIPT},
	{"ADD_EXISTING", Tr::ADD_EXISTING},
	{"ADD_EXISTING_FUNSCRIPTS", Tr::ADD_EXISTING_FUNSCRIPTS},
	{"REMOVE_SCRIPT_CONFIRM_MSG", Tr::REMOVE_SCRIPT_CONFIRM_MSG},
	{"REMOVE", Tr::REMOVE},
	{"REMOVE_SCRIPT", Tr::REMOVE_SCRIPT},
	{"EDIT", Tr::EDIT},
	{"SAVE_FRAME_AS_IMAGE", Tr::SAVE_FRAME_AS_IMAGE},
	{"OPEN_SCREENSHOT_DIR", Tr::OPEN_SCREENSHOT_DIR},
	{"SAVE_HEATMAP", Tr::SAVE_HEATMAP},
	{"UNDO", Tr::UNDO},
	{"REDO", Tr::REDO},
	{"CUT", Tr::CUT},
	{"PASTE", Tr::PASTE},
	{"SELECT", Tr::SELECT},
	{"SELECT_ALL", Tr::SELECT_ALL},
	{"DESELECT_ALL", Tr::DESELECT_ALL},
	{"SPECIAL", Tr::SPECIAL},
	{"SELECT_ALL_LEFT", Tr::SELECT_ALL_LEFT},
	{"SELECT_ALL_RIGHT", Tr::SELECT_ALL_RIGHT},
	{"SET_SELECTION_START", Tr::SET_SELECTION_START},
	{"SET_SELECTION_END", Tr::SET_SELECTION_END},
	{"TOP_POINTS_ONLY", Tr::TOP_POINTS_ONLY},
	{"MID_POINTS_ONLY", Tr::MID_POINTS_ONLY},
	{"BOTTOM_POINTS_ONLY", Tr::BOTTOM_POINTS_ONLY},
	{"BOOKMARKS", Tr::BOOKMARKS},
	{"EXPORT_CLIP", Tr::EXPORT_CLIP},
	{"NAME", Tr::NAME},
	{"ADD_BOOKMARK", Tr::ADD_BOOKMARK},
	{"CREATE_INTERVAL_FOR_FMT", Tr::CREATE_INTERVAL_FOR_FMT},
	{"GO_TO_MENU", Tr::GO_TO_MENU},
	{"NO_BOOKMARKS", Tr::NO_BOOKMARKS},
	{"ALWAYS_SHOW_LABELS", Tr::ALWAYS_SHOW_LABELS},
	{"DELETE_ALL_BOOKMARKS", Tr::DELETE_ALL_BOOKMARKS},
	{"VIEW_MENU", Tr::VIEW_MENU},
	{"METADATA", Tr::METADATA},
	{"DRAW_VIDEO", Tr::DRAW_VIDEO},
	{"RESET_VIDEO_POS", Tr::RESET_VIDEO_POS},
	{"VIDEO_MODE", Tr::VIDEO_MODE},
	{"VIDEO_MODE_FULL", Tr::VIDEO_MODE_FULL},
	{"VIDEO_MODE_LEFT_PANE", Tr::VIDEO_MODE_LEFT_PANE},
	{"VIDEO_MODE_RIGHT_PANE", Tr::VIDEO_MODE_RIGHT_PANE},
	{"VIDEO_MODE_TOP_PANE", Tr::VIDEO_MODE_TOP_PANE},
	{"VIDEO_MODE_BOTTOM_PANE", Tr::VIDEO_MODE_BOTTOM_PANE},
	{"VIDEO_MODE_VR", Tr::VIDEO_MODE_VR},
	{"DEBUG", Tr::DEBUG},
	{"METRICS", Tr::METRICS},
	{"LOG_OUTPUT", Tr::LOG_OUTPUT},
	{"FULLSCREEN", Tr::FULLSCREEN},
	{"PREFERENCES", Tr::PREFERENCES},
	{"REPEAT_RATE", Tr::REPEAT_RATE},
	{"CONTROLLER_CONNECTED", Tr::CONTROLLER_CONNECTED},
	{"EXTENSIONS_MENU", Tr::EXTENSIONS_MENU},
	{"DEV_MODE", Tr::DEV_MODE},
	{"SHOW_LOGS", Tr::SHOW_LOGS},
	{"DEV_MODE_TOOLTIP", Tr::DEV_MODE_TOOLTIP},
	{"EXTENSION_DIR", Tr::EXTENSION_DIR},
	{"ENABLED", Tr::ENABLED},
	{"SHOW_WINDOW", Tr::SHOW_WINDOW},
	{"OPEN_DIRECTORY", Tr::OPEN_DIRECTORY},
	{"NAVIGATION", Tr::NAVIGATION},
	{"SCRIPTING", Tr::SCRIPTING},
	{"UNSAVED_CHANGES_FMT", Tr::UNSAVED_CHANGES_FMT},
	{"METADATA_EDITOR", Tr::METADATA_EDITOR},
	{"TITLE", Tr::TITLE},
	{"DURATION", Tr::DURATION},
	{"CREATOR", Tr::CREATOR},
	{"URL", Tr::URL},
	{"VIDEO_URL", Tr::VIDEO_URL},
	{"NOTES", Tr::NOTES},
	{"LICENSE", Tr::LICENSE},
	{"FREE", Tr::FREE},
	{"PAID", Tr::PAID},
	{"NONE", Tr::NONE},
	{"TAGS", Tr::TAGS},
	{"ADD", Tr::ADD},
	{"PERFORMERS", Tr::PERFORMERS},
	{"SAVE_TEMPLATE", Tr::SAVE_TEMPLATE},
	{"SAVE_TEMPLATE_TOOLTIP", Tr::SAVE_TEMPLATE_TOOLTIP},
	{"GIT_COMMIT", Tr::GIT_COMMIT},
	{"INTERVAL", Tr::INTERVAL},
	{"CLOSE_WITHOUT_SAVING", Tr::CLOSE_WITHOUT_SAVING},
	{"CLOSE_WITHOUT_SAVING_MSG", Tr::CLOSE_WITHOUT_SAVING_MSG},
	{"CONFIGURATION", Tr::CONFIGURATION},
	{"RESET", Tr::RESET},
	{"MOVE", Tr::MOVE},
	{"DISTANCE", Tr::DISTANCE},
	{"GLOBAL_YAW", Tr::GLOBAL_YAW},
	{"GLOBAL_PITCH", Tr::GLOBAL_PITCH},
	{"BOX", Tr::BOX},
	{"CONTAINER", Tr::CONTAINER},
	{"TWIST", Tr::TWIST},
	{"ROLL_DEG", Tr::ROLL_DEG},
	{"PITCH_DEG", Tr::PITCH_DEG},
	{"TWIST_DEG", Tr::TWIST_DEG},
	{"ROLL", Tr::ROLL},
	{"PITCH", Tr::PITCH},
	{"YAW", Tr::YAW},
	{"INSERT_CURRENT_POSITION", Tr::INSERT_CURRENT_POSITION},
	{"SCROLL_PERCENT", Tr::SCROLL_PERCENT},
	{"SCROLL_PERCENT_TOOLTIP", Tr::SCROLL_PERCENT_TOOLTIP},
	{"EXTENSION_LOG_OUTPUT", Tr::EXTENSION_LOG_OUTPUT},
	{"ERROR_STR", Tr::ERROR_STR},
	{"TRY_RELOADING", Tr::TRY_RELOADING},
	{"RELOAD", Tr::RELOAD},
	{"BPM", Tr::BPM},
	{"OFFSET", Tr::OFFSET},
	{"SNAP", Tr::SNAP},
	{"UNKNOWN_ERROR", Tr::UNKNOWN_ERROR},
	{"FFMPEG_WAS_NOT_FOUND_MSG", Tr::FFMPEG_WAS_NOT_FOUND_MSG},
	{"BINDABLE_FUNCTIONS", Tr::BINDABLE_FUNCTIONS},
	{"YES", Tr::YES},
	{"FFMPEG_FAILED_TO_DOWNLOAD_MSG", Tr::FFMPEG_FAILED_TO_DOWNLOAD_MSG},
	{"DONE", Tr::DONE},
	{"DONE_MSG", Tr::DONE_MSG},
	{"EXTRACT_FAIL", Tr::EXTRACT_FAIL},
	{"EXTRACT_FAIL_MSG", Tr::EXTRACT_FAIL_MSG},
	{"DOWNLOAD_FFMPEG", Tr::DOWNLOAD_FFMPEG},
	{"TEMPO_WHOLE_MEASURES", Tr::TEMPO_WHOLE_MEASURES},
	{"TEMPO_2ND_MEASURES", Tr::TEMPO_2ND_MEASURES},
	{"TEMPO_4TH_MEASURES", Tr::TEMPO_4TH_MEASURES},
	{"TEMPO_8TH_MEASURES", Tr::TEMPO_8TH_MEASURES},
	{"TEMPO_12TH_MEASURES", Tr::TEMPO_12TH_MEASURES},
	{"TEMPO_16TH_MEASURES", Tr::TEMPO_16TH_MEASURES},
	{"TEMPO_24TH_MEASURES", Tr::TEMPO_24TH_MEASURES},
	{"TEMPO_32ND_MEASURES", Tr::TEMPO_32ND_MEASURES},
	{"TEMPO_48TH_MEASURES", Tr::TEMPO_48TH_MEASURES},
	{"TEMPO_64TH_MEASURES", Tr::TEMPO_64TH_MEASURES},
	{"LOAD_CONFIG", Tr::LOAD_CONFIG},
	{"SAVE_CONFIG", Tr::SAVE_CONFIG},
	{"SAVE_SIMULATOR_CONFIG", Tr::SAVE_SIMULATOR_CONFIG},
	{"SAVE_SIMULATOR_CONFIG_MSG", Tr::SAVE_SIMULATOR_CONFIG_MSG},
	{"LINES", Tr::LINES},
	{"TEXT", Tr::TEXT},
	{"FRONT", Tr::FRONT},
	{"BACK", Tr::BACK},
	{"BORDER", Tr::BORDER},
	{"INDICATOR", Tr::INDICATOR},
	{"LINE", Tr::LINE},
	{"WIDTH", Tr::WIDTH},
	{"OPACITY", Tr::OPACITY},
	{"EXTRA_LINES", Tr::EXTRA_LINES},
	{"VANILLA", Tr::VANILLA},
	{"SHOW_POSITION", Tr::SHOW_POSITION},
	{"VANILLA_TOOLTIP", Tr::VANILLA_TOOLTIP},
	{"RESET_TO_DEFAULTS", Tr::RESET_TO_DEFAULTS},
	{"SIMULATOR", Tr::SIMULATOR},
	{"APPLICATION", Tr::APPLICATION},
	{"DARK_MODE", Tr::DARK_MODE},
	{"LIGHT_MODE", Tr::LIGHT_MODE},
	{"PREFERENCES_TXT", Tr::PREFERENCES_TXT},
	{"VSYNC", Tr::VSYNC},
	{"VSYNC_TOOLTIP", Tr::VSYNC_TOOLTIP},
	{"FRAME_LIMIT", Tr::FRAME_LIMIT},
	{"FRAME_LIMIT_TOOLTIP", Tr::FRAME_LIMIT_TOOLTIP},
	{"FONT", Tr::FONT},
	{"CHANGE", Tr::CHANGE},
	{"CHOOSE_FONT", Tr::CHOOSE_FONT},
	{"DEFAULT_FONT", Tr::DEFAULT_FONT},
	{"FONT_SIZE", Tr::FONT_SIZE},
	{"FORCE_HW_DECODING", Tr::FORCE_HW_DECODING},
	{"FORCE_HW_DECODING_TOOLTIP", Tr::FORCE_HW_DECODING_TOOLTIP},
	{"FAST_FRAME_STEP", Tr::FAST_FRAME_STEP},
	{"FAST_FRAME_STEP_TOOLTIP", Tr::FAST_FRAME_STEP_TOOLTIP},
	{"SHOW_METADATA_DIALOG_ON_NEW_PROJECT", Tr::SHOW_METADATA_DIALOG_ON_NEW_PROJECT},
	{"FUNCTIONS_RANGE_EXTENDER", Tr::FUNCTIONS_RANGE_EXTENDER},
	{"FUNCTIONS_SIMPLIFY", Tr::FUNCTIONS_SIMPLIFY},
	{"RANGE", Tr::RANGE},
	{"RANGE_EXTENDER_TXT", Tr::RANGE_EXTENDER_TXT},
	{"EPSILON", Tr::EPSILON},
	{"SIMPLIFY_TXT", Tr::SIMPLIFY_TXT},
	{"SPECIAL_FUNCTIONS", Tr::SPECIAL_FUNCTIONS},
	{"MEMORY_USAGE", Tr::MEMORY_USAGE},
	{"UPDATE", Tr::UPDATE},
	{"SLOWEST", Tr::SLOWEST},
	{"LANGUAGE", Tr::LANGUAGE},
	{"ACTION_RELOAD_TRANSLATION", Tr::ACTION_RELOAD_TRANSLATION},
	{"DIRECTORY", Tr::DIRECTORY},
	{"HIGHLIGHT_TRESHOLD", Tr::HIGHLIGHT_TRESHOLD},
	{"ENABLE_MAX_SPEED_HIGHLIGHT", Tr::ENABLE_MAX_SPEED_HIGHLIGHT},
	{"FPS_OVERRIDE", Tr::FPS_OVERRIDE},
	{"TIME_SPENT", Tr::TIME_SPENT},
	{"SHOW_ACTION_LINES", Tr::SHOW_ACTION_LINES},
	{"SHOW_ACTION_POINTS", Tr::SHOW_ACTION_POINTS},
	{"CLEAR_RECENT_FILES", Tr::CLEAR_RECENT_FILES},
	{"GENERIC_OPEN", Tr::GENERIC_OPEN},
	{"ADD_EDIT_TRIGGER", Tr::ADD_EDIT_TRIGGER},
	{"VALIDATE", Tr::VALIDATE},
	{"OK_RESULT", Tr::OK_RESULT},
	{"ORPHAN_TRIGGER_MESSAGE", Tr::ORPHAN_TRIGGER_MESSAGE},
	{"DELETE", Tr::DELETE},
	{"REPEAT", Tr::REPEAT},
	{"WEBSOCKET_API", Tr::WEBSOCKET_API},
	{"SERVER_ACTIVE", Tr::SERVER_ACTIVE},
	{"CLIENT_COUNT", Tr::CLIENT_COUNT},
	{"START", Tr::START},
	{"END", Tr::END},
	{"TOTAL", Tr::TOTAL},
	{"REMOVE_CHAPTER", Tr::REMOVE_CHAPTER},
	{"REMOVE_CHAPTER_MSG", Tr::REMOVE_CHAPTER_MSG},
	{"REMOVE_BOOKMARK", Tr::REMOVE_BOOKMARK},
	{"REMOVE_BOOKMARK_MSG", Tr::REMOVE_BOOKMARK_MSG},
	{"ADD_NEW_CHAPTER", Tr::ADD_NEW_CHAPTER},
	{"ADD_NEW_BOOKMARK", Tr::ADD_NEW_BOOKMARK},
	{"SET_CHAPTER_SIZE", Tr::SET_CHAPTER_SIZE},
	{"SAVE_HEATMAP_WITH_CHAPTERS", Tr::SAVE_HEATMAP_WITH_CHAPTERS},
	{"CHAPTERS", Tr::CHAPTERS},
	{"CHAPTER", Tr::CHAPTER},
	{"BEGIN", Tr::BEGIN},
	{"CHAPTER_BINDING_GROUP", Tr::CHAPTER_BINDING_GROUP},
	{"ACTION_CREATE_BOOKMARK", Tr::ACTION_CREATE_BOOKMARK},
	{"ACTION_CREATE_CHAPTER", Tr::ACTION_CREATE_CHAPTER},

};
